version: '3'

services:
  server:
    build: .
    image: sebastian2772/airbnb-clone
    restart: unless-stopped
    labels:
      team.mernlabs.description: 'Backend Service'
    depends_on:
      - postgres
      - redis
    env_file: .env.production

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    labels:
      team.mernlabs.description: 'Postgres Database'
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: pg.env

  redis:
    image: 'redis:alpine'
