version: '3'

services:
  server:
    build: .
    image: sebastian2772/airbnb-clone:latest
    restart: always
    labels:
      team.mernlabs.description: 'Backend Service'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13-alpine
    restart: always
    labels:
      team.mernlabs.description: 'Postgres Database'
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRE_DB=airbnb

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    labels:
      team.mernlabs.description: 'Adminer Database'
    depends_on:
      - postgres
